### ISSUE TITLE
Some error messages

### ISSUE THREAD

**Issue by ong-andrew** [bwesterb/twittermost#14]
Hi there. Great stuff. I got twittermost to work when I was using Mattermost  v5.3x.

Now that I'm on MM v6.x, I'm encountering some error messages I've not seen before.

`@matteruser ping | followers` returns `replyToPost failed: : Invalid RootId parameter`

`@matteruser check` returns `Could not write data file conf/mattermost.json: open conf/mattermost.json: no such file or directory`

`@matteruser follow` returns 
```
panic: runtime error: index out of range [0] with length 0

goroutine 38 [running]:
main.(*Bot).handleFollow(0xc0000aa6e0, 0xc00008a480, 0xc00023d230, 0x0, 0x1)
	/path/go/pkg/mod/github.com/bwesterb/twittermost@v1.0.1/main.go:424 +0x2bd
main.(*Bot).handleWebSocketEvent(0xc0000aa6e0, 0xc0001af0e0)
	/path/go/pkg/mod/github.com/bwesterb/twittermost@v1.0.1/main.go:256 +0x414
main.(*Bot).setupMattermost.func1(0xc0000aa6e0)
	/path/go/pkg/mod/github.com/bwesterb/twittermost@v1.0.1/main.go:181 +0x79
created by main.(*Bot).setupMattermost
	/path/go/pkg/mod/github.com/bwesterb/twittermost@v1.0.1/main.go:175 +0x4a6
```

I know you are probably not maintaining this project, but was wondering if you know of any tweaks I could do?

Thank you.

**Comment by bwesterb** [comment]
Hi, thanks for reporting this. I can't reproduce — I'm running MM 6.0.0. Could you perhaps try rebuilding? I just updated dependencies.
